version : '3.8'
services:
  sender-service:
    build: .
    ports:
      - '8080:8080'
    environment:
      RABBITHOST: rabbitmq
    depends_on:
      - rabbitmq
      
  receiver-service:
    build: .
    ports:
      - '8081:8081'
    environment:
      RABBITHOST: rabbitmq
    depends_on:
      - rabbitmq
    
  rabbitmq:
    image: rabbitmq:3.9.27-management
    ports:
      - '5672:5672'
      - '15672:15672'
    